name: Build and Deploy React + .NET API to Azure Web App (Windows, OIDC)

on:
  push:
    paths:
    - 'SourceCode/React/**'
    - 'SourceCode/dotnet/**'
  workflow_dispatch:

env:
  DOTNET_PROJECT_PATH: "SourceCode/dotnet/CyberTrackAPI.csproj"
  REACT_APP_PATH: "SourceCode/React/react-frontend"
  PUBLISH_DIR: "publishOutput"

jobs:

  build:
    runs-on: windows-latest

    env:
      DB_CONNECTION_STRING: ${{ secrets.DB_CONNECTION_STRING }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      - name: Install React dependencies
        run: |
          cd ${{ env.REACT_APP_PATH }}
          npm install --legacy-peer-deps

      - name: Build React
        run: |
          cd ${{ env.REACT_APP_PATH }}
          npm run build

      - name: Copy React build into .NET wwwroot
        run: |
          robocopy "${{ env.REACT_APP_PATH }}\build" "$(Split-Path $env:DOTNET_PROJECT_PATH)\wwwroot" /E | Out-Null
          $global:LASTEXITCODE = 0
        shell: powershell


      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'

      - name: Restore .NET dependencies
        run: dotnet restore "${{ env.DOTNET_PROJECT_PATH }}"

      - name: Build .NET API
        run: dotnet build "${{ env.DOTNET_PROJECT_PATH }}" --configuration Release

      - name: Publish .NET API
        run: dotnet publish "${{ env.DOTNET_PROJECT_PATH }}" -c Release -o ${{ env.PUBLISH_DIR }}

      - name: Upload artifact for deployment
        uses: actions/upload-artifact@v4
        with:
          name: publishOutput
          path: ${{ env.PUBLISH_DIR }}/*


  deploy:
    runs-on: windows-latest
    needs: build


    steps:
      - name: Download published artifact
        uses: actions/download-artifact@v4
        with:
          name: publishOutput
          path: ${{ env.PUBLISH_DIR }}


      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'CyberTrack'
          slot-name: 'Production'
          package: ${{ env.PUBLISH_DIR }}
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_7097147C2B244DCB91F612DAB269AEF1 }}

