# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy

name: Build and deploy ASP.Net Core app to Azure Web App - CyberTrack

on:
  push:
    branches:
      - main
  workflow_dispatch:

env:
  PROJECT_PATH: "./Source Code/dotnet/CyberTrackAPI.csproj"
  
jobs:
  build:
    runs-on: windows-latest
    permissions:
      contents: read

    steps:
      - uses: actions/checkout@v4

      - name: Set up .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '10.x'

      - name: Build API
        run: dotnet build "${{ env.PROJECT_PATH }}" --configuration Release

      - name: Publish API
        run: dotnet publish "${{ env.PROJECT_PATH }}" -c Release -o "publish_output"

      - name: Upload artifact for deployment
        uses: actions/upload-artifact@v4
        with:
          name: publish_output
          path: publish_output/*

  deploy:
    runs-on: windows-latest
    needs: build
    permissions:
      id-token: write
      contents: read

    steps:
      - name: Download published app
        uses: actions/download-artifact@v4
        with:
          name: publish_output
          path: publish_output

      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_26B1FFDCDD7C4180803A0A1EE5E73EB0 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_0F57AEBB809946388058CBC5F08E154E }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_C558CA21C7764E9DB67621A7B221B956 }}

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'CyberTrack'
          slot-name: 'Production'
          package: './publish_output'
          clean: true
